# Generated by Django 6.0.5 on 2026-06-02 00:48

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0031_vendor_model_document_fk_swappable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBankAccountModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('financial_institution', models.CharField(blank=True, help_text='Name of the financial institution (i.e. Bank Name).', max_length=100, null=True, verbose_name='Financial Institution')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Account Number')),
                ('routing_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Routing Number')),
                ('aba_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ABA Number')),
                ('swift_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='SWIFT Number')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'), ('cert_deposit', 'Certificate of Deposit'), ('credit_card', 'Credit Card'), ('st_loan', 'Short Term Loan'), ('lt_loan', 'Long Term Loan'), ('mortgage', 'Mortgage'), ('other', 'Other')], default='checking', max_length=20, verbose_name='Account Type')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('active', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('account_model', models.ForeignKey(help_text='Account model be used to map transactions from financial institution', on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.accountmodel', verbose_name='Associated Account Model')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Entity Model')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'abstract': False,
                'indexes': [models.Index(fields=['account_type'], name='swappable_b_account_85bffd_idx'), models.Index(fields=['account_model'], name='swappable_b_account_1d8bc0_idx'), models.Index(fields=['entity_model'], name='swappable_b_entity__bc32af_idx')],
                'unique_together': {('entity_model', 'account_model', 'account_number', 'routing_number'), ('entity_model', 'account_number')},
            },
        ),
    ]
