# Generated by Django 6.0.5 on 2026-06-02 11:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0036_item_transaction_model_swappable'),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_CUSTOMERMODEL_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEstimateModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.SlugField(editable=False, max_length=20, verbose_name='Estimate Number')),
                ('terms', models.CharField(choices=[('fixed', 'Fixed Price'), ('target', 'Target Price'), ('t&m', 'Time & Materials'), ('other', 'Other')], max_length=10, verbose_name='Contract Terms')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='EstimateModel Title length must be greater than 5')], verbose_name='Customer Estimate Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('void', 'Void'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Estimate Model Status')),
                ('date_draft', models.DateField(blank=True, null=True, verbose_name='Date Draft')),
                ('date_in_review', models.DateField(blank=True, null=True, verbose_name='Date In Review')),
                ('date_approved', models.DateField(blank=True, null=True, verbose_name='Date Approved')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('date_canceled', models.DateField(blank=True, null=True, verbose_name='Date Canceled')),
                ('date_void', models.DateField(blank=True, null=True, verbose_name='Date Void')),
                ('revenue_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Total revenue estimate')),
                ('labor_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated labor cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Labor Cost of labor estimate')),
                ('material_estimate', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated material cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Material Cost Estimate')),
                ('equipment_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated equipment cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Equipment Cost Estimate')),
                ('other_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated equipment cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Other Cost Estimate')),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('external_quote_ref', models.CharField(blank=True, max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.DJANGO_LEDGER_CUSTOMERMODEL_MODEL, verbose_name='Customer')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Entity Model')),
            ],
            options={
                'verbose_name': 'Customer Job',
                'verbose_name_plural': 'Customer Jobs',
                'ordering': ['-updated'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='swappable_e_status_ae509a_idx'), models.Index(fields=['customer'], name='swappable_e_custome_1080e9_idx'), models.Index(fields=['terms'], name='swappable_e_terms_5120a3_idx'), models.Index(fields=['entity'], name='swappable_e_entity__4c03b3_idx'), models.Index(fields=['date_draft'], name='swappable_e_date_dr_da5f61_idx'), models.Index(fields=['date_in_review'], name='swappable_e_date_in_9ef5f5_idx'), models.Index(fields=['date_approved'], name='swappable_e_date_ap_1fcb4b_idx'), models.Index(fields=['date_canceled'], name='swappable_e_date_ca_a0c46e_idx'), models.Index(fields=['date_void'], name='swappable_e_date_vo_5c892c_idx'), models.Index(fields=['estimate_number'], name='swappable_e_estimat_101eab_idx')],
                'unique_together': {('entity', 'estimate_number')},
            },
        ),
    ]
