# Generated by Django 6.0.5 on 2026-06-01 23:12

import django.core.validators
import django.db.models.deletion
import django_ledger.models.customer
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0029_stagedtransactionmodel_matched_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCustomerModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('sales_tax_rate', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=1.0)], verbose_name='Sales Tax Rate')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.SlugField(blank=True, null=True, unique=True, verbose_name='User defined customer code')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(editable=False, help_text='System generated customer number.', max_length=30, verbose_name='Customer Number')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=django_ledger.models.customer.customer_picture_upload_to)),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('entity_model', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Customer Entity')),
            ],
            options={
                'verbose_name': 'Customer',
                'abstract': False,
                'indexes': [models.Index(fields=['entity_model', 'customer_number'], name='swappable_c_entity__5283cf_idx'), models.Index(fields=['created'], name='swappable_c_created_f1416b_idx'), models.Index(fields=['updated'], name='swappable_c_updated_bced19_idx'), models.Index(fields=['active'], name='swappable_c_active_415b09_idx'), models.Index(fields=['hidden'], name='swappable_c_hidden_eab6ca_idx')],
                'unique_together': {('entity_model', 'customer_number')},
            },
        ),
    ]
