# Generated by Django 6.0.5 on 2026-06-02 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0032_bank_account_model_import_job_fk_swappable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUnitOfMeasureModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Unit of Measure Name')),
                ('unit_abbr', models.SlugField(max_length=10, verbose_name='UoM Abbreviation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='UoM Entity')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['entity'], name='swappable_u_entity__17c81f_idx')],
                'unique_together': {('entity', 'unit_abbr')},
            },
        ),
    ]
