# Generated by Django 6.0.5 on 2026-06-02 00:13

import django.core.validators
import django.db.models.deletion
import django_ledger.models.vendor
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0030_customer_model_document_fk_swappable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVendorModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('financial_institution', models.CharField(blank=True, help_text='Name of the financial institution (i.e. Bank Name).', max_length=100, null=True, verbose_name='Financial Institution')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Account Number')),
                ('routing_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Routing Number')),
                ('aba_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ABA Number')),
                ('swift_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='SWIFT Number')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'), ('cert_deposit', 'Certificate of Deposit'), ('credit_card', 'Credit Card'), ('st_loan', 'Short Term Loan'), ('lt_loan', 'Long Term Loan'), ('mortgage', 'Mortgage'), ('other', 'Other')], default='checking', max_length=20, verbose_name='Account Type')),
                ('tax_id_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tax Registration Number')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.SlugField(blank=True, null=True, verbose_name='User defined vendor code.')),
                ('vendor_number', models.CharField(blank=True, editable=False, help_text='System generated vendor number.', max_length=30, null=True, verbose_name='Vendor Number')),
                ('vendor_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=django_ledger.models.vendor.vendor_picture_upload_to)),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('entity_model', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Vendor Entity')),
            ],
            options={
                'verbose_name': 'Vendor',
                'abstract': False,
                'indexes': [models.Index(fields=['entity_model', 'vendor_number'], name='swappable_v_entity__077b24_idx'), models.Index(fields=['vendor_number'], name='swappable_v_vendor__0f1d6b_idx'), models.Index(fields=['created'], name='swappable_v_created_9a9a19_idx'), models.Index(fields=['updated'], name='swappable_v_updated_f031b9_idx'), models.Index(fields=['active'], name='swappable_v_active_6562b2_idx'), models.Index(fields=['hidden'], name='swappable_v_hidden_7e51fb_idx')],
                'unique_together': {('entity_model', 'vendor_number')},
            },
        ),
    ]
