# Generated by Django 6.0.5 on 2026-06-02 10:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0034_item_model_item_transaction_fk_swappable'),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_CUSTOMERMODEL_MODEL),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_ITEMMODEL_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInvoiceModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Due')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Paid')),
                ('amount_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Receivable')),
                ('amount_unearned', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Unearned')),
                ('amount_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Earned')),
                ('accrue', models.BooleanField(default=False, verbose_name='Accrue')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)], verbose_name='Progress Amount')),
                ('terms', models.CharField(choices=[('on_receipt', 'Due On Receipt'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days')], default='on_receipt', max_length=10, verbose_name='Terms')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.SlugField(editable=False, max_length=20, verbose_name='Invoice Number')),
                ('invoice_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('void', 'Void'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Invoice Status')),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='Invoice Additional Info')),
                ('date_draft', models.DateField(blank=True, null=True, verbose_name='Draft Date')),
                ('date_in_review', models.DateField(blank=True, null=True, verbose_name='In Review Date')),
                ('date_approved', models.DateField(blank=True, null=True, verbose_name='Approved Date')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('date_void', models.DateField(blank=True, null=True, verbose_name='Void Date')),
                ('date_canceled', models.DateField(blank=True, null=True, verbose_name='Canceled Date')),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('e_document_status', models.CharField(blank=True, max_length=32)),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_cash_account', to='django_ledger.accountmodel', verbose_name='Cash Account')),
                ('ce_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.estimatemodel', verbose_name='Associated Customer Job/Estimate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.DJANGO_LEDGER_CUSTOMERMODEL_MODEL, verbose_name='Customer')),
                ('entity_model', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('invoice_items', models.ManyToManyField(through='django_ledger.ItemTransactionModel', through_fields=('invoice_model', 'item_model'), to=settings.DJANGO_LEDGER_ITEMMODEL_MODEL, verbose_name='Invoice Items')),
                ('ledger', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.ledgermodel', verbose_name='Ledger')),
                ('prepaid_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_prepaid_account', to='django_ledger.accountmodel', verbose_name='Prepaid Account')),
                ('unearned_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_unearned_account', to='django_ledger.accountmodel', verbose_name='Unearned Account')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-updated'],
                'abstract': False,
                'indexes': [
                    models.Index(fields=['invoice_status'], name='swappable_i_invoice_c93b42_idx'),
                    models.Index(fields=['terms'], name='swappable_i_terms_4e7212_idx'),
                    models.Index(fields=['cash_account'], name='swappable_i_cash_ac_856f1d_idx'),
                    models.Index(fields=['prepaid_account'], name='swappable_i_prepaid_b530ed_idx'),
                    models.Index(fields=['unearned_account'], name='swappable_i_unearne_337619_idx'),
                    models.Index(fields=['date_due'], name='swappable_i_date_du_427014_idx'),
                    models.Index(fields=['date_draft'], name='swappable_i_date_dr_e1b81d_idx'),
                    models.Index(fields=['date_in_review'], name='swappable_i_date_in_de5ea1_idx'),
                    models.Index(fields=['date_approved'], name='swappable_i_date_ap_b9175d_idx'),
                    models.Index(fields=['date_paid'], name='swappable_i_date_pa_4bee07_idx'),
                    models.Index(fields=['date_canceled'], name='swappable_i_date_ca_e120af_idx'),
                    models.Index(fields=['date_void'], name='swappable_i_date_vo_ec40d5_idx'),
                    models.Index(fields=['customer'], name='swappable_i_custome_b7a409_idx'),
                    models.Index(fields=['invoice_number'], name='swappable_i_invoice_160bd9_idx'),
                ],
            },
        ),
    ]
