# Generated by Django 6.0.5 on 2026-06-02 09:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0033_unit_of_measure_model_item_fk_swappable'),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_UNITOFMEASUREMODEL_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItemModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal ID')),
                ('item_number', models.CharField(editable=False, max_length=30, verbose_name='Item Number')),
                ('item_role', models.CharField(blank=True, choices=[('expense', 'Expense'), ('inventory', 'Inventory'), ('service', 'Service'), ('product', 'Product')], max_length=10, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('L', 'Labor'), ('M', 'Material'), ('E', 'Equipment'), ('S', 'Lump Sum'), ('O', 'Other')], max_length=1, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU Code')),
                ('upc', models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Default monetary value per unit of measure')),
                ('for_inventory', models.BooleanField(help_text='It is an item you require for your inventory.', verbose_name='Is an item for inventory')),
                ('is_product_or_service', models.BooleanField(help_text='Is a product or service you sell or provide to customers.', verbose_name='Is a product or service.')),
                ('sold_as_unit', models.BooleanField(default=False)),
                ('inventory_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Total inventory received.')),
                ('inventory_received_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total value of inventory received.')),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='Item Additional Info')),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('cogs_account', models.ForeignKey(blank=True, help_text='COGS account where cost will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_cogs_account', to='django_ledger.accountmodel', verbose_name='COGS Account')),
                ('earnings_account', models.ForeignKey(blank=True, help_text='Earnings account where revenue will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_earnings_account', to='django_ledger.accountmodel', verbose_name='Earnings Account')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Item Entity')),
                ('expense_account', models.ForeignKey(blank=True, help_text='Expense account where cost will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_expense_account', to='django_ledger.accountmodel', verbose_name='Expense Account')),
                ('inventory_account', models.ForeignKey(blank=True, help_text='Inventory account where cost will be capitalized.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_inventory_account', to='django_ledger.accountmodel', verbose_name='Inventory Account')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.DJANGO_LEDGER_UNITOFMEASUREMODEL_MODEL, verbose_name='Unit of Measure')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['item_number'], name='swappable_i_item_nu_339574_idx'), models.Index(fields=['item_type'], name='swappable_i_item_ty_dfb63c_idx'), models.Index(fields=['item_role'], name='swappable_i_item_ro_a2e3fe_idx'), models.Index(fields=['upc'], name='swappable_i_upc_1915c4_idx'), models.Index(fields=['sku'], name='swappable_i_sku_58bf46_idx'), models.Index(fields=['for_inventory'], name='swappable_i_for_inv_225af3_idx'), models.Index(fields=['is_product_or_service'], name='swappable_i_is_prod_ba4896_idx'), models.Index(fields=['is_active'], name='swappable_i_is_acti_6f4b24_idx')],
                'unique_together': {('entity', 'item_number')},
            },
        ),
    ]
