# Generated by Django 6.0.5 on 2026-06-02 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0037_estimate_model_document_fk_swappable'),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_ESTIMATEMODEL_MODEL),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_ITEMMODEL_MODEL),
        migrations.swappable_dependency(settings.DJANGO_LEDGER_VENDORMODEL_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBillModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Due')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Paid')),
                ('amount_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Receivable')),
                ('amount_unearned', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Unearned')),
                ('amount_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Earned')),
                ('accrue', models.BooleanField(default=False, verbose_name='Accrue')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)], verbose_name='Progress Amount')),
                ('terms', models.CharField(choices=[('on_receipt', 'Due On Receipt'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days')], default='on_receipt', max_length=10, verbose_name='Terms')),
                ('date_due', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.SlugField(editable=False, max_length=20, verbose_name='Bill Number')),
                ('bill_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=10, verbose_name='Bill Status')),
                ('xref', models.SlugField(blank=True, null=True, verbose_name='External Reference Number')),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='Bill Additional Info')),
                ('date_draft', models.DateField(blank=True, null=True, verbose_name='Draft Date')),
                ('date_in_review', models.DateField(blank=True, null=True, verbose_name='In Review Date')),
                ('date_approved', models.DateField(blank=True, null=True, verbose_name='Approved Date')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('date_void', models.DateField(blank=True, null=True, verbose_name='Void Date')),
                ('date_canceled', models.DateField(blank=True, null=True, verbose_name='Canceled Date')),
                ('custom_marker', models.CharField(default='custom', max_length=32)),
                ('supplier_document_ref', models.CharField(blank=True, max_length=64)),
                ('bill_items', models.ManyToManyField(through='django_ledger.ItemTransactionModel', through_fields=('bill_model', 'item_model'), to=settings.DJANGO_LEDGER_ITEMMODEL_MODEL, verbose_name='Bill Items')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bill_cash_account', to='django_ledger.accountmodel', verbose_name='Cash Account')),
                ('ce_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.DJANGO_LEDGER_ESTIMATEMODEL_MODEL, verbose_name='Associated Customer Job/Estimate')),
                ('entity_model', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('ledger', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.ledgermodel', verbose_name='Ledger')),
                ('prepaid_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bill_prepaid_account', to='django_ledger.accountmodel', verbose_name='Prepaid Account')),
                ('unearned_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bill_unearned_account', to='django_ledger.accountmodel', verbose_name='Unearned Account')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_LEDGER_VENDORMODEL_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-updated'],
                'abstract': False,
                'indexes': [models.Index(fields=['bill_status'], name='swappable_b_bill_st_3636de_idx'), models.Index(fields=['terms'], name='swappable_b_terms_093bf7_idx'), models.Index(fields=['cash_account'], name='swappable_b_cash_ac_1bbce5_idx'), models.Index(fields=['prepaid_account'], name='swappable_b_prepaid_b2a55a_idx'), models.Index(fields=['unearned_account'], name='swappable_b_unearne_7bb1ae_idx'), models.Index(fields=['date_due'], name='swappable_b_date_du_fbb063_idx'), models.Index(fields=['date_draft'], name='swappable_b_date_dr_16cce6_idx'), models.Index(fields=['date_in_review'], name='swappable_b_date_in_9bd3fd_idx'), models.Index(fields=['date_approved'], name='swappable_b_date_ap_0c2e75_idx'), models.Index(fields=['date_paid'], name='swappable_b_date_pa_416775_idx'), models.Index(fields=['date_canceled'], name='swappable_b_date_ca_609ec0_idx'), models.Index(fields=['date_void'], name='swappable_b_date_vo_923cab_idx'), models.Index(fields=['vendor'], name='swappable_b_vendor__f4c760_idx'), models.Index(fields=['bill_number'], name='swappable_b_bill_nu_d6f311_idx')],
            },
        ),
    ]
